<th><span class='v48fv_20x20_new'></span></th>
<th>
	<input type='text' name='phrases[new][phrase]' value='' />
</th>
<?php if($this->application()->slug=='redactor'):?>
<th>
	<select name='phrases[new][style]'>
		<option value='blackout'>Black Out</option>
		<option value='censor'>Censor</option>
		<?php if($this->application()->slug!='censor') : ?>
		<option value='spoiler'>Spoiler</option>
		<?php endif; ?>
		<option value='swap'>Swap with--&gt;</option>
	</select>
</th>
<th>
	<input type='text' name='phrases[new][replacement]' value=''/>
</th>
<?php endif;?>
<th>
</th>
<th>
	<input	type='text'
			name='phrases[new][priority]'
			class="number"
			value='0'/>
</th>
<th></th>
